### ISSUE TITLE
Wondering about the freeze operation

### ISSUE THREAD

**Issue by ElliottYan** [apeterswu/Depth_Growing_NMT#1]
Hi, 
I'm really interested in your work and fascinated by the strong improvement in your paper. But when reading your code, I have the following question:

If I understand the scripts correctly, you first train the shallow model, then replace the parameter in the deep model. Finally, you directly train the deep model. However, I didn't see any code about the operation about freeze operation as you described in your paper.

"in Stage 1, the bottom module (i.e., enc1 and dec1) is trained and subsequently holds constant; in Stage 2, only the top module (i.e., enc2 and dec2) is optimized."

Am I missing some details in your code? 

Looking forward to your reply. Thanks

**Comment by apeterswu** [comment]
Hi, ElliottYan

Thanks for your interest and sorry for the late reply. 
Please refer to https://github.com/apeterswu/Depth_Growing_NMT/blob/master/deepNMT/fairseq/trainer_deep.py#L307 for a reference.
As you can see, in the second stage, we use `train_deep.py` script to train the deep model. During it, the `trainer_deep` will ignore the gradients of the bottom module and update the upper module only.
If you have further questions, please let me know.

**Comment by ElliottYan** [comment]
OK. Thanks for your reply! 
I do miss this detail in your code. Close this issue.
