### ISSUE TITLE
train first several steps

### ISSUE THREAD

**Issue by chen1234yue** [apeterswu/Depth_Growing_NMT#2]
I'm really interested in your work. But I don't understand why we need to 'train first several steps of the deep model with eight layers. For example, train only 10 steps.'

**Comment by alphadl** [comment]
this is like the warmup training procedure

**Comment by apeterswu** [comment]
As @alphadl mentioned, the first several steps are trained as a pre-step which is used to get the overall 8-layer model parameters, then we will initialize the first 6-layer parameters of the 8-layer model (the next step 'Prepare the deep model.' with `build_initial_ckpt_for_deep.sh`).

**Comment by chen1234yue** [comment]
Thanks.I will close the issue
